# List of url's to posters used for preference tuning
def preferenceTuningPosters():
    return [
        ('https://imgs.search.brave.com/fw3zN0uOwFKoIAcsjUK27eyBalIZfrzu55vnQ-pYgqg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtbmEuc3NsLWlt/YWdlcy1hbWF6b24u/Y29tL2ltYWdlcy9J/LzgxYUhldUowQ0dM/LmpwZw', 'Oppenheimer', 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.'),
        ('https://imgs.search.brave.com/bY-g_9l2aRiMqh5v4U8ZNOXSjyLS50eT6Sqc9qp9kA4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy90aXRh/bmljLWZhY3RzLW1v/dmllLXBvc3Rlci0x/NTEyNjY0MjQ2Lmpw/Zz9jcm9wPTAuOTQ1/eHc6MC45NTV4aDsw/LjAyODd4dywwLjAx/Njd4aCZyZXNpemU9/OTgwOio', 'Titanic', 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.'),
        ('https://imgs.search.brave.com/fsfXFyz3O3g5cYrfd-pvPw-Eyh9eoFMxVqMELv579CY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1Qk1qSXdNakUx/TnpjNE5WNUJNbDVC/YW5CblhrRnRaVGd3/TkRnNE9UQTFOek1A/LmpwZw', 'The Lion King', 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself. A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: No worries for the rest of your days. But when his past comes to haunt him, the young prince must decide his fate: Will he remain an outcast or face his demons and become what he needs to be?'),
        ('https://imgs.search.brave.com/pbA7p0uoB5HP1uEe2EOwTAOsNE-Coe6-8xqcbhOWBA8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1Qk0yTXlOall4/Tm1VdFlUQXdOaTAw/TVRZeExXSm1OV1l0/WXpabE9EWTNaVGsz/T1RGbFhrRXlYa0Zx/Y0dkZVFYVnlOemt3/TWpRNU56TUAuanBn', 'The Godfather', 'Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son, Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.'), 
        ('https://imgs.search.brave.com/3vNTQPgREOv9oYhvDjVlOioq9F5UmiB16GdAOhar-Qc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1QlpETXlaR0pq/T0dJdFlqSmtaQzAw/TURWbExXRTBZMll0/WkdJd01ERXhZV0Uz/TUdRM1hrRXlYa0Zx/Y0dkZVFYVnlORFl5/TURrNU1UVUAuanBn', 'Jurassic Park', "An industrialist invites some experts to visit his theme park of cloned dinosaurs. After a power failure, the creatures run loose, putting everyone's lives, including his grandchildren's, in danger."), 
        ('https://cdn.prod.website-files.com/6009ec8cda7f305645c9d91b/66a4263d01a185d5ea22eeef_6408f676b5811234c887ca62_top%2520gun%2520maverick-min.png', 'Top Gun: Maverick', 'The story involves Maverick confronting his past while training a group of younger Top Gun graduates, including the son of his deceased best friend, for a dangerous mission.'), 
        ('https://imgs.search.brave.com/QX0RXW6vr2GwWZx46WqBQSh9nPqv4evZH6ZDLk4TMQQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGVw/aGVua2luZy5jb20v/aW1hZ2VzL21vdmll/cy90aGVhdHJpY2Fs/X21vdmllL3RoZV9z/aGF3c2hhbmtfcmVk/ZW1wdGlvbi91czIu/anBn', 'The Shawshank Redemption', 'A Maine banker convicted of the murder of his wife and her lover in 1947 gradually forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.'), 
        ('https://imgs.search.brave.com/w4s-Y69uwePCFWHB0qKu1N79ujllOIGN5R3-3t8QDG8/rs:fit:860:0:0:0/g:ce/aHR0cDovL3d3dy5p/bXBhd2FyZHMuY29t/LzIwMDgvcG9zdGVy/cy9kYXJrX2tuaWdo/dC5qcGc', 'The Dark Knight', 'Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as "The Joker" appears in Gotham, creating a new wave of chaos.')
    ]